version: '3.7'

networks:
  chat_network:

services:
  chat-backend:
    image: chat-backend
    container_name: chat-backend
    ports:
      - 3000:3000
    restart: always
    networks:
      chat_network:
    volumes:
      - '.:/app'
