version: '3.7'

networks:
  chat_network:

services:
  chat-backend:
    build: .
    container_name: chat-backend
    ports:
      - 3333:3333
    restart: always
    networks:
      chat_network:
    volumes:
      - '.:/app'
