name: SSH

description: run commands via ssh

inputs:
  user:
    description: remote machine user
    required: true

  host:
    description: remote host
    required: true

  port:
    description: ssh server port
    required: false
    default: 22

  key:
    description: ssh private key
    required: true

  commands:
    description: commands to execute on the remote host
    required: true

runs:
  using: composite
  steps:
    - name: create ssh key file
      shell: bash
      run: |
        # create a key file name if necessary
        if [[ -z ${SSH_ACTION_KEY_NAME+x} ]]; then
          SSH_ACTION_KEY_NAME="SSH_KEY_$RANDOM";
          echo "SSH_ACTION_KEY_NAME=$SSH_ACTION_KEY_NAME" >> $GITHUB_ENV;
        fi

        mkdir ~/.ssh -p
        echo "${{ inputs.key }}" >> ~/.ssh/$SSH_ACTION_KEY_NAME
        sudo chmod 600 ~/.ssh/$SSH_ACTION_KEY_NAME

    - name: execute command
      shell: bash
      run: |
        ssh -i ~/.ssh/$SSH_ACTION_KEY_NAME \
        -o PubKeyAuthentication=yes -o StrictHostKeyChecking=no -o RequestTTY=no \
        ${{ inputs.user }}@${{ inputs.host }} -p ${{ inputs.port }} "${{ inputs.commands }}"

    - name: delete ssh key file
      if: always()
      shell: bash
      run: |
        rm ~/.ssh/$SSH_ACTION_KEY_NAME
