name: GitHub Actions Demo
on:
  push:
    branches:
      - main

env:
  KEY: ${{ secrets.SSH_KEY }}
  USER: ${{ secrets.SSH_USER }}
  HOST: ${{ secrets.SSH_HOST }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Connecting on server
        run: ssh ${{ env.USER }}@${{ env.HOST }} -i ${{ env.KEY }}

      - name: List files on server
        run: ls -la
