name: Deploy
on:
  push:
    branches:
      - main

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Install docker and docker-compose
        uses: ./.github/actions/docker
        with:
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_key: ${{ secrets.SSH_KEY }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Setup
    environment: production
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Make new image tag
        shell: bash
        run: echo "NEW_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: production/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/chat-backend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/chat-backend:${{ env.NEW_IMAGE_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/chat-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/chat-backend:buildcache,mode=max

      - name: Create nginx config files
        env:
          SERVER_NAME: ${{ secrets.SSL_CERTIFICATE_ADDRESS }}
        shell: bash
        run: |
          cd production/nginx/conf.d

          # make sure envsubst don't replace these nginx variables
          export uri='$uri'
          export host='$host'

          envsubst < http.conf.template > http.conf
          envsubst < https.conf.template > https.conf.disabled
          rm http.conf.template https.conf.template

      - name: Create config files
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_API_URL: ${{ secrets.APP_API_URL }}

        shell: bash
        run: |
          cd production
          envsubst < .env.template > .env
          rm .env.template

      - name: Copy scripts to remote server
        uses: ./.github/actions/rsync
        with:
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          source: production
          destination: ~/app/

      - name: Setup remote container
        uses: ./.github/actions/ssh
        with:
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          command: |
            cd app/production

            # update the containers
            docker-compose down
            docker pull ${{ secrets.DOCKERHUB_USER }}/chat-backend:latest
            docker-compose up -d

      - name: Install SSL certificate
        uses: ./.github/actions/ssl
        with:
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_key: ${{ secrets.SSH_KEY }}
          certificate_address: ${{ secrets.SSL_CERTIFICATE_ADDRESS }}
          email: ${{ secrets.SSL_CERTIFICATE_EMAIL }}

      - name: Setup files and remove unused images
        uses: ./.github/actions/ssh
        with:
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          command: |
            cd ~/app/production

            mv nginx/conf.d/https.conf.disabled nginx/conf.d/https.conf && docker-compose restart nginx

            docker image prune -af
