name: GitHub Actions Demo
on:
  push:
    branches:
      - main

env:
  KEY: ${{ secrets.SSH_KEY }}
  USER: ${{ secrets.SSH_USER }}
  HOST: ${{ secrets.SSH_HOST }}
  KEY_NAME: chatkey

jobs:
  Server_connection:
    runs-on: ubuntu-latest
    steps:
      - name: List files on local machine
        shell: bash
        run: ls -la

      - name: Create ssh folder
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo '${{ env.KEY }}' > ~/.ssh/${{ env.KEY_NAME }}
          sudo chmod 600 ~/.ssh/${{ env.KEY_NAME }}

      - name: Connecting on server
        shell: bash
        run: |
          ssh ${{ env.USER }}@${{ env.HOST }} \
          -o PubKeyAuthentication=yes \
          -o RequestTTY=no \
          -o StrictHostKeyChecking=no \
          -i ~/.ssh/${{ env.KEY_NAME }} \
          ls -la
