name: GitHub Actions Demo
on:
  push:
    branches:
      - main

env:
  KEY: ${{ secrets.SSH_KEY }}
  USER: ${{ secrets.SSH_USER }}
  HOST: ${{ secrets.SSH_HOST }}

jobs:
  Server_connection:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Make new image tag
        shell: bash
        run: echo "NEW_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: production/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/chat-backend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/chat-backend:${{ env.NEW_IMAGE_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/chat-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/chat-backend:buildcache,mode=max

      # - name: Copy scripts to remote server
      #   uses: ./.github/actions/rsync
      #   with:
      #     user: ${{ secrets.SSH_USER }}
      #     host: ${{ secrets.SSH_HOST }}
      #     key: ${{ secrets.SSH_KEY }}
      #     source: production/scripts
      #     destination: ~/todo/production

      # - name: Create ssh folder
      #   shell: bash
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo '${{ env.KEY }}' > ~/.ssh/${{ env.KEY_NAME }}
      #     sudo chmod 600 ~/.ssh/${{ env.KEY_NAME }}

      # - name: Connecting on server
      #   shell: bash
      #   run: |
      #     ssh ${{ env.USER }}@${{ env.HOST }} \
      #     -o PubKeyAuthentication=yes \
      #     -o RequestTTY=no \
      #     -o StrictHostKeyChecking=no \
      #     -i ~/.ssh/${{ env.KEY_NAME }} \
      #     ls -la
